-- =============================================================================
-- meta database  –  Neptune ETL reference schema  (v4)
-- =============================================================================
-- Database role: READ-ONLY for the ETL script.
--
-- Changes in v4
-- ─────────────
-- • gsr_client_id and gsr_inst_id UUID columns added to all tables that are
--   queried by the ETL pipeline (entity_mapping, attribute_mapping, entity_tag,
--   concept_tag).  Every query filters on both columns so a single meta
--   database can serve multiple tenants without row-level security.
-- • Two new tables: meta.concept_tag, meta.entity_tag (concept/node tagging).
-- • privacy_class and security_class added to meta.attribute_mapping
--   (attribute-level hybrid tagging).
--
-- Design rules
-- ────────────
-- • All PKs / FKs are UUID, generated by gen_random_uuid() (pgcrypto).
-- • No password columns anywhere.
-- • All timestamps are TIMESTAMP (no time zone), stored as UTC.
-- • Operational / write tables live in the separate "run" database.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS meta;

-- ---------------------------------------------------------------------------
-- 1. DATA SOURCES
--    One row per business database reached by the ETL pipeline.
--    Not tenant-filtered: a data source is a shared infrastructure resource
--    that may be referenced by multiple tenants' mappings.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.data_source (
    source_id       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    source_name     VARCHAR(100)    NOT NULL UNIQUE,
    description     TEXT,
    driver_module   VARCHAR(200)    NOT NULL,
    host            VARCHAR(255),
    port            INTEGER,
    database_name   VARCHAR(255),
    -- Secrets Manager secret name/ARN or env-var prefix; never a literal password.
    secret_ref      VARCHAR(500)    NOT NULL,
    extra_params    JSONB,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

COMMENT ON TABLE  meta.data_source IS 'Business databases that source data for the graph ETL.';
COMMENT ON COLUMN meta.data_source.secret_ref IS
    'Secrets Manager secret name/ARN or env-var prefix. Never a literal password.';


-- ---------------------------------------------------------------------------
-- 2. SOURCE TABLES
--    A table, view, or SQL query inside a data source.
--    Not tenant-filtered: shared infrastructure; tenants reference via mappings.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.source_table (
    table_id         UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id        UUID            NOT NULL REFERENCES meta.data_source(source_id),
    schema_name      VARCHAR(255),
    table_name       VARCHAR(255)    NOT NULL,
    override_query   TEXT,
    partition_column VARCHAR(255),
    partition_size   INTEGER         NOT NULL DEFAULT 100000,
    description      TEXT,
    is_active        BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at       TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    UNIQUE (source_id, schema_name, table_name)
);

COMMENT ON COLUMN meta.source_table.partition_column IS
    'Numeric/date column for range partitioning; NULL = fetchmany batching.';


-- ---------------------------------------------------------------------------
-- 3. GRAPH ENTITIES
--    A Neptune node label or edge label.
--    Not tenant-filtered: labels are shared graph vocabulary.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.graph_entity (
    entity_id       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_name     VARCHAR(255)    NOT NULL UNIQUE,
    entity_type     VARCHAR(10)     NOT NULL CHECK (entity_type IN ('node', 'edge')),
    from_node_label VARCHAR(255),
    to_node_label   VARCHAR(255),
    description     TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

COMMENT ON TABLE  meta.graph_entity IS 'A Neptune node label or edge label.';
COMMENT ON COLUMN meta.graph_entity.entity_type     IS '"node" or "edge".';
COMMENT ON COLUMN meta.graph_entity.from_node_label IS 'Source node label (edges only).';
COMMENT ON COLUMN meta.graph_entity.to_node_label   IS 'Target node label (edges only).';


-- ---------------------------------------------------------------------------
-- 4. ENTITY MAPPINGS
--    Links a source table to a graph entity for a specific tenant.
--    TENANT-FILTERED: gsr_client_id + gsr_inst_id required on every query.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.entity_mapping (
    mapping_id           UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant scope ──────────────────────────────────────────────────────────
    -- Both columns are required.  Every ETL query filters on both.
    -- gsr_client_id  identifies the client organisation.
    -- gsr_inst_id    identifies the specific instance / environment of that
    --                client (e.g. production vs. staging).
    gsr_client_id        UUID            NOT NULL,
    gsr_inst_id          UUID            NOT NULL,

    table_id             UUID            NOT NULL REFERENCES meta.source_table(table_id),
    entity_id            UUID            NOT NULL REFERENCES meta.graph_entity(entity_id),

    -- Python eval expression producing the Neptune ~id from a source row dict.
    -- Column names are local variables.  Example: "'Cust_' + str(customer_id)"
    id_column_expr       VARCHAR(500)    NOT NULL,

    -- Edge-only: expressions for ~from and ~to Neptune node IDs.
    from_id_column_expr  VARCHAR(500),
    to_id_column_expr    VARCHAR(500),

    -- Optional SQL WHERE fragment appended to the base query.
    row_filter           TEXT,

    -- Change-detection mode ─────────────────────────────────────────────────
    -- 'timestamp'  WHERE <watermark_column> > last_watermark
    -- 'hash'       Full scan + SHA-256; detects inserts, updates, and deletes
    -- 'full'       Always re-upserts; deletes by id-set difference
    change_mode          VARCHAR(20)     NOT NULL DEFAULT 'hash'
                             CHECK (change_mode IN ('timestamp', 'hash', 'full')),

    watermark_column     VARCHAR(255),   -- required for change_mode = 'timestamp'
    delete_flag_column   VARCHAR(255),   -- truthy column marks deleted rows
    hash_columns         TEXT[],         -- columns hashed; NULL = all attributes

    description          TEXT,
    is_active            BOOLEAN         NOT NULL DEFAULT TRUE,
    load_order           INTEGER         NOT NULL DEFAULT 100,
    created_at           TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at           TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),

    UNIQUE (gsr_client_id, gsr_inst_id, table_id, entity_id)
);

COMMENT ON COLUMN meta.entity_mapping.gsr_client_id      IS 'Tenant client UUID; all ETL queries filter on this.';
COMMENT ON COLUMN meta.entity_mapping.gsr_inst_id        IS 'Tenant instance UUID; all ETL queries filter on this.';
COMMENT ON COLUMN meta.entity_mapping.change_mode        IS '"timestamp", "hash", or "full".';
COMMENT ON COLUMN meta.entity_mapping.watermark_column   IS 'Source timestamp column for change_mode=timestamp.';
COMMENT ON COLUMN meta.entity_mapping.delete_flag_column IS 'Truthy column/expr marks deleted rows (timestamp mode only).';
COMMENT ON COLUMN meta.entity_mapping.load_order         IS 'Lower values run first; nodes must precede their edges.';

CREATE INDEX idx_entity_mapping_tenant ON meta.entity_mapping (gsr_client_id, gsr_inst_id);


-- ---------------------------------------------------------------------------
-- 5. ATTRIBUTE MAPPINGS
--    One source column → one Neptune property, per entity mapping.
--    TENANT-FILTERED: inherits tenant scope from entity_mapping; queried with
--    explicit gsr_client_id / gsr_inst_id for defence-in-depth.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.attribute_mapping (
    attr_id             UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant scope (mirrors entity_mapping; enables direct tenant-filtered queries)
    gsr_client_id       UUID            NOT NULL,
    gsr_inst_id         UUID            NOT NULL,

    mapping_id          UUID            NOT NULL REFERENCES meta.entity_mapping(mapping_id),
    source_column       VARCHAR(500)    NOT NULL,
    target_property     VARCHAR(255)    NOT NULL,
    data_type           VARCHAR(50)     NOT NULL DEFAULT 'String'
                            CHECK (data_type IN (
                                'String','Byte','Short','Int','Long',
                                'Float','Double','Bool','Date','DateTime'
                            )),
    is_id_component     BOOLEAN         NOT NULL DEFAULT FALSE,
    nullable            BOOLEAN         NOT NULL DEFAULT TRUE,
    transform_expr      TEXT,

    -- Attribute-level classification (hybrid tagging model)
    -- Emitted as companion Neptune properties:
    --   <target_property>__privacy_class   e.g. "email__privacy_class"  = "PII"
    --   <target_property>__security_class  e.g. "email__security_class" = "CONFIDENTIAL"
    -- NULL means no classification; no companion property is written.
    --
    -- Recommended privacy_class values:
    --   PII, QUASI_PII, SENSITIVE, NON_PII
    --
    -- Recommended security_class values:
    --   PUBLIC, INTERNAL, CONFIDENTIAL, SECRET
    privacy_class       VARCHAR(50),
    security_class      VARCHAR(50),

    description         TEXT,
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at          TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),

    UNIQUE (mapping_id, target_property)
);

COMMENT ON COLUMN meta.attribute_mapping.gsr_client_id  IS 'Tenant client UUID; matches parent entity_mapping.';
COMMENT ON COLUMN meta.attribute_mapping.gsr_inst_id    IS 'Tenant instance UUID; matches parent entity_mapping.';
COMMENT ON COLUMN meta.attribute_mapping.privacy_class  IS
    'Privacy classification, e.g. PII. Emitted as <property>__privacy_class on the Neptune node.';
COMMENT ON COLUMN meta.attribute_mapping.security_class IS
    'Security classification, e.g. CONFIDENTIAL. Emitted as <property>__security_class on the Neptune node.';

CREATE INDEX idx_attr_mapping_tenant  ON meta.attribute_mapping (gsr_client_id, gsr_inst_id);
CREATE INDEX idx_attr_mapping_mapping ON meta.attribute_mapping (mapping_id);


-- ---------------------------------------------------------------------------
-- 6. CONCEPT TAGS
--    Controlled vocabulary of node-level concept tags, grouped by category.
--    TENANT-FILTERED: each tenant maintains its own tag vocabulary.
--
--    Recommended tag_category values:
--      business_domain     Finance, Customer, Product, Logistics, …
--      data_classification PII, Sensitive, Public  (node-level; not attribute)
--      security_class      Public, Internal, Confidential  (node-level)
--      ontology_class      Person, Organisation, Event, Asset, …
-- ---------------------------------------------------------------------------
CREATE TABLE meta.concept_tag (
    tag_id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant scope
    gsr_client_id   UUID            NOT NULL,
    gsr_inst_id     UUID            NOT NULL,

    -- Short machine-friendly name, unique within (tenant, category).
    -- Becomes the 'name' property of the :ConceptTag Neptune node.
    tag_name        VARCHAR(100)    NOT NULL,

    -- Groups tags into orthogonal classification axes.
    tag_category    VARCHAR(100)    NOT NULL,

    -- Human-readable label for UIs; falls back to tag_name when NULL.
    display_name    VARCHAR(200),

    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),

    UNIQUE (gsr_client_id, gsr_inst_id, tag_category, tag_name)
);

COMMENT ON TABLE  meta.concept_tag IS 'Tenant-scoped controlled vocabulary of concept tags.';
COMMENT ON COLUMN meta.concept_tag.gsr_client_id IS 'Tenant client UUID.';
COMMENT ON COLUMN meta.concept_tag.gsr_inst_id   IS 'Tenant instance UUID.';
COMMENT ON COLUMN meta.concept_tag.tag_name      IS 'Unique name within (tenant, category); used as Neptune node name property.';
COMMENT ON COLUMN meta.concept_tag.tag_category  IS 'Classification axis, e.g. business_domain, ontology_class.';

CREATE INDEX idx_concept_tag_tenant   ON meta.concept_tag (gsr_client_id, gsr_inst_id);
CREATE INDEX idx_concept_tag_category ON meta.concept_tag (gsr_client_id, gsr_inst_id, tag_category, is_active);


-- ---------------------------------------------------------------------------
-- 7. ENTITY TAGS
--    Assigns concept tags to entity mappings.
--    Nodes produced by a tagged mapping receive :TAGGED_AS edges in Neptune.
--    TENANT-FILTERED.
-- ---------------------------------------------------------------------------
CREATE TABLE meta.entity_tag (
    entity_tag_id   UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant scope
    gsr_client_id   UUID            NOT NULL,
    gsr_inst_id     UUID            NOT NULL,

    mapping_id      UUID            NOT NULL REFERENCES meta.entity_mapping(mapping_id),
    tag_id          UUID            NOT NULL REFERENCES meta.concept_tag(tag_id),

    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP       NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),

    UNIQUE (gsr_client_id, gsr_inst_id, mapping_id, tag_id)
);

COMMENT ON TABLE  meta.entity_tag IS 'Assigns concept tags to entity mappings; :TAGGED_AS edges are written in Neptune.';
COMMENT ON COLUMN meta.entity_tag.gsr_client_id IS 'Tenant client UUID.';
COMMENT ON COLUMN meta.entity_tag.gsr_inst_id   IS 'Tenant instance UUID.';

CREATE INDEX idx_entity_tag_tenant  ON meta.entity_tag (gsr_client_id, gsr_inst_id);
CREATE INDEX idx_entity_tag_mapping ON meta.entity_tag (mapping_id);
CREATE INDEX idx_entity_tag_tag     ON meta.entity_tag (tag_id);


-- ---------------------------------------------------------------------------
-- General indexes
-- ---------------------------------------------------------------------------
CREATE INDEX idx_source_table_source   ON meta.source_table   (source_id);
CREATE INDEX idx_entity_mapping_table  ON meta.entity_mapping (table_id);
CREATE INDEX idx_entity_mapping_entity ON meta.entity_mapping (entity_id);
CREATE INDEX idx_entity_mapping_order  ON meta.entity_mapping (gsr_client_id, gsr_inst_id, load_order, is_active);
